""" vim settings, not vi
set nocompatible

""" broken with typescript
set re=0

set hidden
set mouse=a
set ttymouse=sgr
set clipboard-=autoselect

""" syntax and colorscheme
syntax on
set termguicolors
colorscheme base16-materia

""" additional setting unless they are overridden
set cursorline
highlight CursorLine cterm=NONE ctermbg=235
highlight ExtraWhitespace ctermbg=red

"""reload changed files
set autoread

""" the command window at the bottom
set laststatus=2
set ruler
set showcmd
set showmode
set noerrorbells
set visualbell
set t_vb=

""" tabbing behavior
set autoindent
set smartindent
set smarttab
set shiftwidth=4
set softtabstop=4
set expandtab
set backspace=2
set showmatch

""" display stuff
set list
set listchars=trail:~,tab:>-
set number
set scrolloff=8
set sidescrolloff=8
set sidescroll=1
set nowrap
set textwidth=0

""" search options
set incsearch
set wrapscan
set nohls
set ignorecase

""" tab completion!
set wildmenu
set wildmode=longest,list,full
set path=$PWD/**

if has("autocmd")
    filetype plugin indent on
endif

let g:colors = getcompletion('', 'color')
func! NextColors()
    let idx = index(g:colors, g:colors_name)
    return (idx + 1 >= len(g:colors) ? g:colors[0] : g:colors[idx + 1])
endfunc
func! PrevColors()
    let idx = index(g:colors, g:colors_name)
    return (idx - 1 < 0 ? g:colors[-1] : g:colors[idx - 1 ])
endfunc
nnoremap <C-n> :exe "colorscheme " .. NextColors()<CR>
nnoremap <C-p> :exe "colorscheme " .. PrevColors()<CR>
